apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Cache-Control: no-cache, no-store, must-revalidate";
        more_set_headers "Pragma: no-cache";
        more_set_headers "Expires: 0";
spec:
  ingressClassName: nginx-testhub
  rules:
    - host: jenkins.testhub.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jenkins
                port:
                  number: 8080